import random
a = open('atlas_data/Atlas_A.txt','r')
b = open('atlas_data/Atlas_B.txt','r')
c = open('atlas_data/Atlas_C.txt','r')
d = open('atlas_data/Atlas_D.txt','r')
e = open('atlas_data/Atlas_E.txt','r')
f = open('atlas_data/Atlas_F.txt','r')
g = open('atlas_data/Atlas_G.txt','r')
h = open('atlas_data/Atlas_H.txt','r')
i = open('atlas_data/Atlas_I.txt','r')
j = open('atlas_data/Atlas_J.txt','r')
k = open('atlas_data/Atlas_K.txt','r')
l = open('atlas_data/Atlas_L.txt','r')
m = open('atlas_data/Atlas_M.txt','r')
n = open('atlas_data/Atlas_N.txt','r')
o = open('atlas_data/Atlas_O.txt','r')
p = open('atlas_data/Atlas_P.txt','r')
q = open('atlas_data/Atlas_Q.txt','r')
r = open('atlas_data/Atlas_R.txt','r')
s = open('atlas_data/Atlas_S.txt','r')
t = open('atlas_data/Atlas_T.txt','r')
u = open('atlas_data/Atlas_U.txt','r')
v = open('atlas_data/Atlas_V.txt','r')
w = open('atlas_data/Atlas_W.txt','r')
x = open('atlas_data/Atlas_X.txt','r')
y = open('atlas_data/Atlas_Y.txt','r')
z = open('atlas_data/Atlas_Z.txt','r')
a = list(a.read().split())
b = list(b.read().split())
c = list(c.read().split())
d = list(d.read().split())
e = list(e.read().split())
f = list(f.read().split())
g = list(g.read().split())
h = list(h.read().split())
i = list(i.read().split())
j = list(j.read().split())
k = list(k.read().split())
l = list(l.read().split())
m = list(m.read().split())
n = list(n.read().split())
o = list(o.read().split())
p = list(p.read().split())
q = list(q.read().split())
r = list(r.read().split())
s = list(s.read().split())
t = list(t.read().split())
u = list(u.read().split())
v = list(v.read().split())
w = list(w.read().split())
x = list(x.read().split())
y = list(y.read().split())
z = list(z.read().split())
print("Welcome to the Atlas Game!\n The rules are simple: you have to type a word, and then I will type a word that will start with the same letter, as your word ends. This cycle continues. Type 'exit()' to exit Let's begin!")
inp = ""
while inp != "exit()":
    turns = 0
    inp = input('> ')
    inp = inp.lower()
    end = inp[-1]
    if turns == 0:
        global aaa
        aaa = random.choice(globals()[end])
        print(aaa)
    elif turns != 0:
        if aaa[-1] == inp[0]:
            aaa = random.choice(globals()[end])
            print(aaa)
        else:
            print("Wrong word")
